config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jlist.urls')),
]
if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

jlist/urls.py
from django.urls import path, include
from .views import JsonListView, JsonFileUploadView, JsonFileView

app_name = 'jlist'
urlpatterns = [
    path('', JsonListView.as_view(), name='home'),
    path('create/', JsonFileUploadView.as_view(), name='create'),
    path('download/<int:pk>', JsonFileView.as_view(), name='download')
]

jlist/models.py
from django.db import models

# Create your models here.
class Jfile(models.Model):
    PRIVATE_CHOICE = (
        ('PUBLIC','Public'),
        ('PRIVATE','Private')
    )

    jfile = models.FileField(upload_to='json_files/')
    upload_date = models.DateTimeField()
    privacy = models.CharField(max_length=10, choices=PRIVATE_CHOICE, default='PUBLIC')
    user = models.CharField(max_length=255)

    def __str__(self):
        return self.jfile.name
    
    class Meta:
        verbose_name_plural = 'jfiles'
        ordering =['upload_date']

jlist/forms.py
import io
import magic
import mimetypes

from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Jfile

class JfileForm(forms.ModelForm):
    
    class Meta:
        model = Jfile
        fields = ('jfile','privacy')
    
    def file_mime(self, jfile):
        ext = jfile.name.split('.')[1]
        mime = magic.from_buffer(jfile.read(), mime=True)
        if mime == 'text/plain' and ext == 'json':
            return True
        return False
    
    def clean(self):
        cleaned_data = super().clean()
        jfile = cleaned_data.get('jfile')

        if jfile.size > (2**20) or not self.file_mime(jfile):
            raise forms.ValidationError(_('The File is either larger than 1mb or is not JSON format.'), code='invalid')

        return cleaned_data    

jlist/views.py
import datetime
import mimetypes
import os

from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.encoding import smart_str
from django.views.generic import ListView, CreateView, View

from .models import Jfile
from .forms import JfileForm
from wsgiref.util import FileWrapper

# Create your views here.
class JsonListView(ListView):
    model = Jfile
    template_name = 'jsonlist.html'

    def get_queryset(self):
        if not self.request.user.groups.filter(name__in=['JLIST_ADMIN']):
            return Jfile.objects.exclude(privacy='PRIVATE')
        return Jfile.objects.all()

class JsonFileUploadView(CreateView):
    model = Jfile
    form_class = JfileForm
    template_name = 'jfile_form.html'
    success_url = reverse_lazy('jlist:home')

    def form_valid(self, form):
        jfile = form.save(commit=False)
        if self.request.user.username:
            jfile.user = self.request.user.username
        else:
            jfile.user = 'anonymous'
        jfile.upload_date = datetime.datetime.now()
        jfile.save()
        return super().form_valid(form)

class JsonFileView(View):
    def get(self, request, pk):
        file_obj = Jfile.objects.filter(pk=pk).first()
        file_name = file_obj.jfile.name.split('/')[1]
        file_path = '{}/{}'.format(settings.MEDIA_ROOT, file_obj.jfile.name)
        file_wrapper = FileWrapper(open(file_path,'rb'))
        file_mimetypes = mimetypes.guess_type(file_path)

        response = HttpResponse(file_wrapper, content_type=file_mimetypes)
        response['X-Sendfile'] = file_path
        response['Content-Length'] = os.stat(file_path).st_size
        response['Content-Disposition'] = 'attachment; filename={}/'.format(smart_str(file_name))
        return response

jlist/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Json File List</title>
        <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
        <link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">
        <link rel="stylesheet" href="//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css">
    </head>
    <body>
           {% block content %}{% endblock %}
    </body>
</html>

jlist/templates/jfile_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Json File Upload</h2>
    <hr>
    <br>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input class="button-primary" type="submit" value="Submit">
    </form>
</div>
{% endblock %}

jlist/templates/jsonlist.html
{% extends 'base.html' %}
{% load static %}
{% get_media_prefix as MEDIA_PREFIX %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="column column-75">
            <h2>Json Files</h2>
        </div>
        <div class="column">
            <a class="button" href="{% url 'jlist:create' %}">Upload</a>
        </div>
    </div>
    
    <br>
    <table>
        <thead>
            <tr>
                <th>File</th>
                <th>Size</th>
                <th>User</th>
                <th>Uploaded</th>
            </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            <tr>
                <td>
                    <a href="{% url 'jlist:download' pk=item.pk %}">
                        {{ item.jfile.name }}
                    </a>
                </td>
                <td>{{ item.jfile.size }} bytes</td>
                <td>{{ item.user }}</td>
                <td>{{ item.upload_date }}</td>
            </tr>    
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}